FROM python:3-alpine

WORKDIR /workspaces/edelweiss_server

RUN pip install --upgrade pip

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "web_api:app", "--reload", "--host", "0.0.0.0"]