FROM python:3-alpine

WORKDIR /workspace/edelweiss-server/helpers

RUN pip install --upgrade pip

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "webAPI:app", "--reload"]