version: "3"
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: edelweiss-dev-password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=edelweiss-dev-password
