import "./globals.css"

import { Inter } from "next/font/google"
import { headers } from "next/headers"

import type { Session } from "@supabase/auth-helpers-nextjs"
import SupabaseProvider from "@/context/AuthContext"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


const inter = Inter({ subsets: ["latin"] })

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode
  session: Session
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider session={session}>{children}</SupabaseProvider>
      </body>
    </html>
  )
}
