name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: lcZc5QxdJTSprNlLSrcaKAYt
  VERCEL_PROJECT_ID: prj_0dSuB2tq741TQVSIm8FipMnvH2zs
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./edelweiss_webapp
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=OtoXdgr1XSPRqPrbsRfaYyy5
      - name: Build Project Artifacts
        run: vercel build --token=OtoXdgr1XSPRqPrbsRfaYyy5
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=OtoXdgr1XSPRqPrbsRfaYyy5
